### ISSUE TITLE
[PCGS parsing] "Silver" ends up in Variety field for cert 49827012

### ISSUE THREAD

**Issue by dhun1849** [rising-sun-rarities/numisnavigator-public#106]
This could be a PCGS data issue, not sure.  It's repeatable.

<img width="373" alt="Screenshot 2025-01-05 at 9 23 12 AM" src="https://github.com/user-attachments/assets/d6e2e26f-af83-401b-aa73-b11d50ef6ddc" />

Actually, sure enough PCGS has listed Silver in the variety field on their side, so NN is doing the right thing.  I don't thing we need to do anything, other than implement a policy allowing the user to fix this.  That would be covered by https://github.com/rising-sun-rarities/numisnavigator-public/issues/105

**Comment by rising-sun-rarities** [comment]
fixed

**Comment by dhun1849** [comment]
Almost fixed.  When I refetch, Silver is no longer showing in the Variety field.  But if I then save changes, and go back to edit, I still see Silver in the Variety field.

Also occurs if I just manually delete Silver from the Variety field and save, then go back to edit again.

**Comment by rising-sun-rarities** [comment]
Fixed
