### ISSUE TITLE
[View Coin] Purchase date isn't updated on view coin page after edit

### ISSUE THREAD

**Issue by dhun1849** [rising-sun-rarities/numisnavigator-public#132]
I just added a coin with today's date as the purchase date.  I later went back and updated the purchase date.  The new date is shown on the edit coin page, but the previous date (as first saved) is shown on the View Coin page.

Edit Coin:
<img width="274" alt="Screenshot 2025-01-06 at 2 02 46 PM" src="https://github.com/user-attachments/assets/1f066f3d-c579-4194-b02c-919d81c8bed0" />

View coin (after save):
<img width="281" alt="Screenshot 2025-01-06 at 2 02 25 PM" src="https://github.com/user-attachments/assets/d066efea-91f0-4f23-a945-3f2f1c204522" />

After refreshing the View Coin page, the updated date is now displayed on View Coin page:
<img width="286" alt="Screenshot 2025-01-06 at 2 03 34 PM" src="https://github.com/user-attachments/assets/27172a6f-29e9-4de8-8867-f1c11627f5a1" />

**Comment by rising-sun-rarities** [comment]
Fixed and also fixed issue where it was converting it to a sales transaction

**Comment by dhun1849** [comment]
Still seeing this, did it committed yet?  

Edit purchase date
Save
View coin (date is not updated)
Refresh web page (now coin is updated)

**Comment by rising-sun-rarities** [comment]
Okay so now its saving properly just not showing until refresh, I'll look into it. 

Before it didnt actually save, thats why going to edit it again still showed the old value

**Comment by rising-sun-rarities** [comment]
fixed
